namespace BFGSDK
{
    public class bfgCommon
    {
        // BFG iOS SDK 6.9.1
        // BFG Android SDK 6.9.1
        public const string UNITY_WRAPPER_VERSION = "6.9.1";

        // bfgBranding callback
        public const string BFGBRANDING_NOTIFICATION_COMPLETED = "BFGBRANDING_NOTIFICATION_COMPLETED";

        // bfgPromodashboard callbacks
        public const string BFGPROMODASHBOARD_NOTIFICATION_COLDSTART = "BFGPROMODASHBOARD_NOTIFICATION_CONTINUE";
        public const string BFGPROMODASHBOARD_NOTIFICATION_WARMSTART = "BFGPROMODASHBOARD_NOTIFICATION_APPLICATION_RESUMED";

        // bfgPurchase callbacks
        public const string NOTIFICATION_PURCHASE_PRODUCTINFORMATION = "NOTIFICATION_PURCHASE_PRODUCTINFORMATION";
        public const string NOTIFICATION_PURCHASE_SUCCEEDED = "NOTIFICATION_PURCHASE_SUCCEEDED";
        public const string NOTIFICATION_PURCHASE_FAILED = "NOTIFICATION_PURCHASE_FAILED";
        public const string NOTIFICATION_RESTORE_SUCCEEDED = "NOTIFICATION_RESTORE_SUCCEEDED";
        public const string NOTIFICATION_RESTORE_FAILED = "NOTIFICATION_RESTORE_FAILED";

        // Deeplink callbacks
        public const string NOTIFICATION_DEEPLINK_ONDEEPLINKRECEIVED = "NOTIFICATION_DEEPLINK_ONDEEPLINKRECEIVED";
        public const string THIRDPARTYTARGETEDADVERTISING = "THIRDPARTYTARGETEDADVERTISING";

        // Rave ADK callbacks
        public const string RAVE_ADK_DELEGATE_ADK_DID_CHANGE = "RAVE_ADK_DELEGATE_ADK_DID_CHANGE";
        public const string RAVE_ADK_DELEGATE_ADK_UNRESOLVED_KEYS = "RAVE_ADK_DELEGATE_ADK_UNRESOLVED_KEYS";
        public const string RAVE_ADK_DELEGATE_FETCH_CURRENT_SUCCEEDED = "RAVE_ADK_DELEGATE_FETCH_CURRENT_SUCCEEDED";
        public const string RAVE_ADK_DELEGATE_FETCH_CURRENT_FAILED = "RAVE_ADK_DELEGATE_FETCH_CURRENT_FAILED";
        public const string RAVE_ADK_DELEGATE_ADK_SELECT_SUCCEEDED = "RAVE_ADK_DELEGATE_ADK_SELECT_SUCCEEDED";
        public const string RAVE_ADK_DELEGATE_ADK_SELECT_FAILED = "RAVE_ADK_DELEGATE_ADK_SELECT_FAILED";

        // bfgRaveDelegate callbacks
        public const string BFG_RAVE_PROFILE_FAILED_WITH_ERROR = "BFG_RAVE_PROFILE_FAILED_WITH_ERROR";
        public const string BFG_RAVE_PROFILE_SUCCEEDED = "BFG_RAVE_PROFILE_SUCCEEDED";
        public const string BFG_RAVE_PROFILE_CANCELLED = "BFG_RAVE_PROFILE_CANCELLED";
        public const string BFG_RAVE_SIGN_IN_COPPA_TRUE = "BFG_RAVE_SIGN_IN_COPPA_TRUE";
        public const string BFG_RAVE_SIGN_IN_COPPA_FALSE = "BFG_RAVE_SIGN_IN_COPPA_FALSE";
        public const string BFG_RAVE_SIGN_IN_CANCELLED = "BFG_RAVE_SIGN_IN_CANCELLED";
        public const string BFG_RAVE_SIGN_IN_SUCCEEDED = "BFG_RAVE_SIGN_IN_SUCCEEDED";
        public const string BFG_RAVE_SIGN_IN_FAILED_WITH_ERROR = "BFG_RAVE_SIGN_IN_FAILED_WITH_ERROR";
        public const string BFG_RAVE_USER_DID_LOGIN = "BFG_RAVE_USER_DID_LOGIN";
        public const string BFG_RAVE_USER_DID_LOGOUT = "BFG_RAVE_USER_DID_LOGOUT";
        public const string BFG_RAVE_USER_LOGIN_ERROR = "BFG_RAVE_USER_LOGIN_ERROR";
        public const string BFG_RAVE_CHANGE_DISPLAY_NAME_DID_SUCCEED = "BFG_RAVE_CHANGE_DISPLAY_NAME_DID_SUCCEED";
        public const string BFG_RAVE_CHANGE_DISPLAY_NAME_DID_FAIL_WITH_ERROR = "BFG_RAVE_CHANGE_DISPLAY_NAME_DID_FAIL_WITH_ERROR";

        // bfgRave setupLoginStatusCallbackWithExternalCallback
        public const string BFG_RAVE_EXTERNALCALLBACK_LOGGEDIN = "BFG_RAVE_EXTERNALCALLBACK_LOGGEDIN";
        public const string BFG_RAVE_EXTERNALCALLBACK_LOGGEDOUT = "BFG_RAVE_EXTERNALCALLBACK_LOGGEDOUT";
        public const string BFG_RAVE_EXTERNALCALLBACK_LOGINERROR = "BFG_RAVE_EXTERNALCALLBACK_LOGINERROR";

        // RaveReadyListener callback
        public const string BFG_RAVE_READY = "BFG_RAVE_READY";

        // bfgPolicyListener callbacks
        public const string BFG_POLICY_LISTENER_WILLSHOWPOLICIES = "BFG_POLICY_LISTENER_WILLSHOWPOLICIES";
        public const string BFG_POLICY_LISTENER_ONPOLICIESCOMPLETED = "BFG_POLICY_LISTENER_ONPOLICIESCOMPLETED";

#if UNITY_ANDROID
        // Android bfgPlacement callbacks
        public const string NOTIFICATION_PLACEMENT_REWARDRECEIVED = "BFG_NOTIFICATION_PLACEMENT_CONTENT_UNLOCK_REWARD";
        public const string NOTIFICATION_PLACEMENT_STARTPURCHASE = "BFG_NOTIFICATION_PLACEMENT_CONTENT_START_PURCHASE";
        public const string NOTIFICATION_PLACEMENT_DIDRECEIVEDATASTRING = "BFG_NOTIFICATION_PLACEMENT_PAYLOAD";

        // Android callbacks for webviews
        public const string BFG_NOTIFICATION_PLACEMENT_CONTENT_OPENED = "BFG_NOTIFICATION_PLACEMENT_CONTENT_OPENED";
        public const string BFG_NOTIFICATION_PLACEMENT_CONTENT_CLOSED = "BFG_NOTIFICATION_PLACEMENT_CONTENT_CLOSED";

        // Android bfgPromoDashboard callbacks
        public const string BFGPROMODASHBOARD_NOTIFICATION_MAINMENU = "BFGPROMODASHBOARD_NOTIFICATION_MAINMENU";
        public const string BFGPROMODASHBOARD_POST_CURRENT_INVENTORY_SUCCEEDED = "BFGPROMODASHBOARD_POST_CURRENT_INVENTORY_SUCCEEDED";

        // Android bfgPurchase extra callback
        public const string NOTIFICATION_POST_CURRENT_INVENTORY_SUCCEEDED = "NOTIFICATION_POST_CURRENT_INVENTORY_SUCCEEDED";

        // Android lifecycle callbacks
        public const string BFG_NOTIFICATION_APP_RESUME = "BFG_APP_RESUME";
        public const string BFG_NOTIFICATION_APP_PAUSE = "BFG_APP_PAUSE";
        public const string BFG_NOTIFICATION_APP_STOP = "BFG_APP_STOP";
#elif UNITY_IOS || UNITY_IPHONE
        // iOS bfgPlacement callbacks
        public const string NOTIFICATION_PLACEMENT_REWARDRECEIVED = "BFG_NOTIFICATION_PLACEMENT_CONTENT_UNLOCK_REWARD";
        public const string NOTIFICATION_PLACEMENT_STARTPURCHASE = "BFG_NOTIFICATION_PLACEMENT_CONTENT_START_PURCHASE";
        public const string NOTIFICATION_PLACEMENT_DIDRECEIVEDATASTRING = "BFG_NOTIFICATION_PLACEMENT_PAYLOAD";

        // iOS only bfgPlacement callbacks
        public const string NOTIFICATION_PLACEMENTCONTENT_DIDDISMISS = "NOTIFICATION_PLACEMENTCONTENT_DIDDISMISS";
        public const string NOTIFICATION_PLACEMENTCONTENT_DIDOPEN = "NOTIFICATION_PLACEMENTCONTENT_DIDOPEN";
        public const string NOTIFICATION_PLACEMENTCONTENT_ERROR = "NOTIFICATION_PLACEMENTCONTENT_ERROR";
        public const string NOTIFICATION_PLACEMENTCONTENT_WILLDISMISS = "NOTIFICATION_PLACEMENTCONTENT_WILLDISMISS";
        public const string NOTIFICATION_PLACEMENTCONTENT_WILLOPEN = "NOTIFICATION_PLACEMENTCONTENT_WILLOPEN";

        // iOS bfgPurchase callback
        public const string NOTIFICATION_FINISH_PURCHASE_COMPLETE = "NOTIFICATION_FINISH_PURCHASE_COMPLETE";

        // iOS bfgPushNotificationDelegate callback
        public const string NOTIFICATION_PUSHNOTIFICATION_DIDRECEIVEPUSHNOTIFICATIONWITHPAYLOAD_WHILEAPPINFOREGROUND = "NOTIFICATION_PUSHNOTIFICATION_DIDRECEIVEPUSHNOTIFICATIONWITHPAYLOAD_WHILEAPPINFOREGROUND";

        // iOS bfgSimplePurchase callbacks
        public const string NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEDIDSUCCEED = "NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEDIDSUCCEED";
        public const string NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEDIDFAIL = "NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEDIDFAIL";
        public const string NOTIFICATION_SIMPLEPURCHASE_SIMPLERESTOREDIDSUCCEED = "NOTIFICATION_SIMPLEPURCHASE_SIMPLERESTOREDIDSUCCEED";
        public const string NOTIFICATION_SIMPLEPURCHASE_SIMPLERESTOREDIDFAIL = "NOTIFICATION_SIMPLEPURCHASE_SIMPLERESTOREDIDFAIL";
        public const string NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEORRESTOREDIDCANCEL = "NOTIFICATION_SIMPLEPURCHASE_SIMPLEPURCHASEORRESTOREDIDCANCEL";
        public const string NOTIFICATION_SIMPLEPURCHASE_STARTUP_COMPLETE = "NOTIFICATION_SIMPLEPURCHASE_STARTUP_COMPLETE";
#else
        // bfgPlacement callbacks for unknown platform
        public const string NOTIFICATION_PLACEMENT_REWARDRECEIVED = "UNKNOWN_PLATFORM";
        public const string NOTIFICATION_PLACEMENT_STARTPURCHASE = "UNKNOWN_PLATFORM";
        public const string NOTIFICATION_PLACEMENT_DIDRECEIVEDATASTRING = "UNKNOWN_PLATFORM";
#endif
    }
}